import { DomainRegistry } from "../src/config/domain-registry.js";
import type { RuntimeConfig } from "../src/config/runtime.js";
import type { DomainPolicy, LinkRecord } from "../src/core/types.js";

export const domainPolicies: readonly DomainPolicy[] = [
  {
    id: 1,
    domainKey: "url6x",
    hostname: "url6x.local",
    label: "URL6X",
    surface: "dashboard",
    active: true,
    allowCreate: false,
    diversionCampaign: "url6x",
    reportTimezone: "UTC",
  },
  {
    id: 2,
    domainKey: "vidx1x",
    hostname: "vidx1x.local",
    label: "VIDX1X",
    surface: "redirect",
    active: true,
    allowCreate: true,
    diversionCampaign: "vidx1x",
    reportTimezone: "UTC",
  },
  {
    id: 3,
    domainKey: "plays9x",
    hostname: "plays9x.local",
    label: "Plays9X",
    surface: "redirect",
    active: true,
    allowCreate: true,
    diversionCampaign: "plays9x",
    reportTimezone: "UTC",
  },
];

export const testConfig: RuntimeConfig = {
  environment: "test",
  appNamespace: "test-shortener",
  host: "127.0.0.1",
  port: 3000,
  logLevel: "silent",
  registry: new DomainRegistry([
    {
      id: 1,
      key: "url6x",
      canonicalHost: "url6x.local",
      aliases: ["www.url6x.local"],
      label: "URL6X",
      surface: "dashboard",
      active: true,
      allowCreate: false,
      publicBaseUrl: "https://url6x.local",
      imageBaseUrl: "https://img.url6x.local",
      emitLocalImageAlt: true,
      compactNoImagePreview: false,
    },
    {
      id: 2,
      key: "vidx1x",
      canonicalHost: "vidx1x.local",
      aliases: ["www.vidx1x.local"],
      label: "VIDX1X",
      surface: "redirect",
      active: true,
      allowCreate: true,
      publicBaseUrl: "https://vidx1x.local",
      imageBaseUrl: "https://vidx1x.local",
      emitLocalImageAlt: false,
      compactNoImagePreview: true,
      creationFallback: true,
    },
    {
      id: 3,
      key: "plays9x",
      canonicalHost: "plays9x.local",
      aliases: [],
      label: "Plays9X",
      surface: "redirect",
      active: true,
      allowCreate: true,
      publicBaseUrl: "https://plays9x.local",
      imageBaseUrl: "https://plays9x.local",
      emitLocalImageAlt: true,
      compactNoImagePreview: false,
      acceptUnprovenDeliveredClaim: true,
    },
  ]),
  trustProxy: false,
  trustCloudflareHeaders: false,
  cloudflareHeaderSanitizationVerified: false,
  originAuth: {
    enabled: false,
    header: "x-shortener-origin-auth",
    expectedSha256: "",
  },
  ipHashSecret: "test-ip-secret-with-at-least-32-characters",
  cookieSigningSecret: "test-cookie-secret-with-at-least-32-chars",
  proxyChainVerified: false,
  storageDriver: "memory",
  mysql: {
    host: "127.0.0.1",
    port: 3306,
    database: "shortener",
    user: "shortener",
    password: "",
    connectionLimit: 2,
    queueLimit: 8,
  },
  redis: {
    url: "redis://127.0.0.1:6379",
    keyPrefix: "test-shortener",
    connectTimeoutMs: 100,
    commandTimeoutMs: 100,
  },
  sessionTtlSeconds: 2_592_000,
  reporting: { deliveredCountryDomainIds: [] },
  operations: {
    pm2ProcessPrefix: "shortener-test",
    webInstances: 1,
    webMaxMemoryMb: 384,
    imageWorkerMaxMemoryMb: 512,
    imageRecoveryPreflightTimeoutMs: 5_000,
  },
  links: {
    codeLength: 6,
    maxBulkLinks: 100,
    maxBulkImages: 100,
  },
  browserScopedDefaultUsers: [{ id: 8, username: "hdvideos", role: "user" }],
  image: {
    executor: "inline",
    privateTempDir: "./private/test",
    publicUploadDir: "./public/uploads",
    maxUploadBytes: 2 * 1024 * 1024,
    maxImagePixels: 20_000_000,
    readyPerSession: 100,
    readyTotal: 1_000,
    ownershipTtlSeconds: 86_400,
    jobTimeoutMs: 30_000,
    serveStaticUploads: false,
  },
  developmentSeed: { username: "", password: "" },
  redirectEngine: "passthrough",
  datacenterRangesFile: "./data/datacenter-ranges.json",
  pilotDiagnostics: { enabled: false, expectedTokenSha256: "" },
  analytics: { enabled: false, measurementId: "", siteKey: "" },
};

export const baseLink: LinkRecord = {
  id: "9007199254740993",
  domainId: 2,
  code: "Ab12Cd3",
  userId: 42,
  destination: "https://destination.example/path?a=1",
  title: "Stored title",
  description: "Stored description",
  image: "uploads/0123456789abcdef.jpg",
  authorRole: "user",
  domainHostname: "vidx1x.local",
  domainLabel: "VIDX1X",
  diversionCampaign: "vidx1x",
  createdAt: new Date("2026-08-23T00:00:00.000Z"),
};
